version: '3'

services:
  mongo:
    container_name: 'mongo'
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  ganache:
    container_name: 'ganache'
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command:
      - "-m"
      - "myth like bonus scare over problem client lizard pioneer submit female collect" # !DON'T USE THIS IN PRODUCTION
      - "--accounts=20"                  # 20 available accounts
      - "--networkId=123456"             # Sets a chain ID of 123456
      - "--defaultBalanceEther=1000"     # Optional: Ensure each account has enough Ether (default is 100).
    networks:
      - app-network

  server:
    container_name: 'server'
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - ganache
    networks:
      - app-network
    volumes:
      - './server:/usr/src/app'

  client:
    container_name: 'client'
    volumes:
      - "./client/src:/usr/src/app/src"
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge
